spring:
  profiles:
    active:
      - dev
---
#注册中心占用7001端口,冒号后面必须要有空格
server:
  port: 7001

spring:
    profiles: dev
    application:
      name: microservicecloud-config-eureka-client

eureka:
  instance:
    hostname: localhost #冒号后面必须要有空格
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: true  #不通过eureka获取注册信息
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 7001 #注册中心占用7001端口,冒号后面必须要有空格
     
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
      
eureka:
  instance:
    hostname: localhost #冒号后面必须要有空格
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: true  #不通过eureka获取注册信息
    service-url:
      defaultZone: http://localhost:7001/eureka/