spring:
  profiles:
    active:
      - dev
---
server:
  port: 8003
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud01?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-cfg.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: MicroService8001
    prefer-ip-address: true

info:
  app.name: microservice-provider-dept
  company.name: www.feashtoo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8002
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud02?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-cfg.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: MicroService8001
    prefer-ip-address: true

info:
  app.name: microservice-provider-dept
  company.name: www.feashtoo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$